const sharp = require('sharp');
const fs = require('fs');
const path = require('path');

const GALLERY_DIR = path.join(__dirname, '..', 'public', 'images', 'gallery');

async function convertGalleryImages() {
    const files = fs.readdirSync(GALLERY_DIR).filter(f => f.endsWith('.jpg'));

    let totalOriginal = 0;
    let totalWebP = 0;

    for (const file of files) {
        const inputPath = path.join(GALLERY_DIR, file);
        const outputPath = path.join(GALLERY_DIR, file.replace('.jpg', '.webp'));
        const stats = fs.statSync(inputPath);
        totalOriginal += stats.size;

        await sharp(inputPath)
            .webp({ quality: 80 })
            .toFile(outputPath);

        const outStats = fs.statSync(outputPath);
        totalWebP += outStats.size;

        console.log(`${file} -> ${file.replace('.jpg', '.webp')} (${(stats.size / 1024).toFixed(0)}KB -> ${(outStats.size / 1024).toFixed(0)}KB)`);
    }

    console.log(`\nTotal: ${(totalOriginal / 1024 / 1024).toFixed(1)}MB -> ${(totalWebP / 1024 / 1024).toFixed(1)}MB (${((1 - totalWebP / totalOriginal) * 100).toFixed(0)}% reduction)`);
}

async function generateBlurData() {
    const files = fs.readdirSync(GALLERY_DIR).filter(f => f.endsWith('.webp'));
    const blurData = {};

    for (const file of files) {
        const inputPath = path.join(GALLERY_DIR, file);
        const buffer = await sharp(inputPath)
            .resize(10, 10, { fit: 'inside' })
            .webp({ quality: 20 })
            .toBuffer();

        blurData[file.replace('.webp', '')] = `data:image/webp;base64,${buffer.toString('base64')}`;
    }

    const outputPath = path.join(__dirname, '..', 'src', 'data', 'blur-data.ts');
    const content = `// Auto-generated by scripts/convert-images.js\nexport const blurData: Record<string, string> = ${JSON.stringify(blurData, null, 2)};\n`;
    fs.writeFileSync(outputPath, content);
    console.log(`\nBlur data written to src/data/blur-data.ts (${Object.keys(blurData).length} entries)`);
}

(async () => {
    console.log('Converting gallery images to WebP...');
    await convertGalleryImages();
    console.log('\nGenerating blur placeholders...');
    await generateBlurData();
})();
